FROM stefanscherer/node-windows:8-nanoserver

WORKDIR /app/

COPY package*.json ./

RUN npm install --production

COPY src/*.js ./

ENV DEBUG_OPTION " "

EXPOSE 3000

CMD ["cmd", "/C", "node %DEBUG_OPTION% server.js"]